stark = House.create(name: "Stark")
lannister = House.create(name: "Lannister")
targaryen = House.create(name: "Targaryen")
tyrell = House.create(name: "Tyrell")
greyjoy = House.create(name: "Greyjoy`")

stark.members.create(name: "Rickard Stark")
stark.members.create(name: "Eddard Stark")
stark.members.create(name: "Catelyn Stark")
stark.members.create(name: "Robb Stark")
stark.members.create(name: "Sansa Stark")
stark.members.create(name: "Arya Stark")
stark.members.create(name: "Brandon Stark")
stark.members.create(name: "Rickon Stark")
stark.members.create(name: "Lyanna Stark")
stark.members.create(name: "Jon Snow")
stark.members.create(name: "Benjen Stark")

lannister.members.create(name: "Tywin Lannister")
lannister.members.create(name: "Joanna Lannister")
lannister.members.create(name: "Cersei Lannister")
lannister.members.create(name: "Joffrey Baratheon")
lannister.members.create(name: "Myrcella Baratheon")
lannister.members.create(name: "Tommen Baratheon")
lannister.members.create(name: "Jaime Lannister")
lannister.members.create(name: "Tyrion Lannister")
lannister.members.create(name: "Kevan Lannister")
lannister.members.create(name: "Lancel Lannister")
lannister.members.create(name: "Martyn Lannister")
lannister.members.create(name: "Willem Lannister")


targaryen.members.create(name: "Aerys Targaryen")
targaryen.members.create(name: "Rhaella Targaryen")
targaryen.members.create(name: "Rhaegar Targaryen")
targaryen.members.create(name: "Rhaenys Targaryen")
targaryen.members.create(name: "Aegon Targaryen")
targaryen.members.create(name: "Viserys Targaryen")
targaryen.members.create(name: "Daenerys Targaryen")
targaryen.members.create(name: "Aemon Targaryen")

tyrell.members.create(name: "Luther Tyrell")
tyrell.members.create(name: "Olenna Tyrell")
tyrell.members.create(name: "Mace Tyrell")
tyrell.members.create(name: "Alerie Tyrell")
tyrell.members.create(name: "Margaery Tyrell")
tyrell.members.create(name: "Loras Tyrell")

greyjoy.members.create(name: "Balon Greyjoy")
greyjoy.members.create(name: "Alannys Greyjoy")
greyjoy.members.create(name: "Rodrik Greyjoy")
greyjoy.members.create(name: "Maron Greyjoy")
greyjoy.members.create(name: "Yara Greyjoy")
greyjoy.members.create(name: "Theon Greyjoy")
greyjoy.members.create(name: "Euron Greyjoy")
