gryffindor = House.create(name: "Gryffindor")
ravenclaw = House.create(name: "Ravenclaw")
hufflepuff = House.create(name: "Hufflepuff")
slytherin = House.create(name: "Slytherin")

gryffindor.students.create(name: "Albus Dumbledore")
gryffindor.students.create(name: "Celestina Warbeck")
gryffindor.students.create(name: "Rubeus Hagrid")
gryffindor.students.create(name: "Minerva McGonagall")
gryffindor.students.create(name: "Arthur Weasley")
gryffindor.students.create(name: "Sirius Black")
gryffindor.students.create(name: "Lily Evans")
gryffindor.students.create(name: "Remus Lupin")
gryffindor.students.create(name: "Peter Pettigrew")
gryffindor.students.create(name: "James Potter")
gryffindor.students.create(name: "Charles Weasley")
gryffindor.students.create(name: "Percy Weasley")
gryffindor.students.create(name: "Oliver Wood")
gryffindor.students.create(name: "Angelina Johnson")
gryffindor.students.create(name: "Lee Jordan")
gryffindor.students.create(name: "Alicia Spinnet")
gryffindor.students.create(name: "Fred Weasley")
gryffindor.students.create(name: "George Weasley")
gryffindor.students.create(name: "Katie Bell")
gryffindor.students.create(name: "Hermione Granger")
gryffindor.students.create(name: "Harry Potter")
gryffindor.students.create(name: "Dean Thomas")
gryffindor.students.create(name: "Ron Weasley")
gryffindor.students.create(name: "Seamus Finnigan")
gryffindor.students.create(name: "Neville Longbottom")
gryffindor.students.create(name: "Parvati Patil")
gryffindor.students.create(name: "Colin Creevey")
gryffindor.students.create(name: "Ginny Weasley")
gryffindor.students.create(name: "Dennis Creevey")

ravenclaw.students.create(name: "Helena Ravenclaw")
ravenclaw.students.create(name: "Myrtle Warren")
ravenclaw.students.create(name: "Gilderoy Lochart")
ravenclaw.students.create(name: "Roger Davies")
ravenclaw.students.create(name: "Penelope Clearwater")
ravenclaw.students.create(name: "Marcus Belby")
ravenclaw.students.create(name: "Cho Chang")
ravenclaw.students.create(name: "Terry Boot")
ravenclaw.students.create(name: "Padma Patil")
ravenclaw.students.create(name: "Luna Lovegood")
ravenclaw.students.create(name: "Filius Flitwick")
ravenclaw.students.create(name: "Xenophilius Lovegood")
ravenclaw.students.create(name: "Sybill Trelawney")

hufflepuff.students.create(name: "Newton Scamander")
hufflepuff.students.create(name: "Pomona Sprout")
hufflepuff.students.create(name: "Nymphadora Tonks")
hufflepuff.students.create(name: "Cedric Diggory")
hufflepuff.students.create(name: "Susan Bones")
hufflepuff.students.create(name: "Hannah Abbott")
hufflepuff.students.create(name: "Justin Finch-Fletchley")
hufflepuff.students.create(name: "Ernie Macmillan")
hufflepuff.students.create(name: "Zacharias Smith")


slytherin.students.create(name: "Gormlaith Gaunt")
slytherin.students.create(name: "Corvinus Gaunt")
slytherin.students.create(name: "Phineas Black")
slytherin.students.create(name: "Leta Letsrange")
slytherin.students.create(name: "Cassiopeia Black")
slytherin.students.create(name: "Lucretia Black")
slytherin.students.create(name: "Horace Slughorn")
slytherin.students.create(name: "Tom Riddle")
slytherin.students.create(name: "Lestrange")
slytherin.students.create(name: "Avery")
slytherin.students.create(name: "Orion Black")
slytherin.students.create(name: "Lucius Malfoy")
slytherin.students.create(name: "Narcissa Black")
slytherin.students.create(name: "Severus Snape")
slytherin.students.create(name: "Felix Rosier")
slytherin.students.create(name: "Barnaby Lee")
slytherin.students.create(name: "Draco Malfoy")
slytherin.students.create(name: "Vincent Crabbe")
slytherin.students.create(name: "Gregory Goyle")
slytherin.students.create(name: "Millicent Bulstrode")
slytherin.students.create(name: "Pansy Parkinson")
slytherin.students.create(name: "Blaise Sabini")


